#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Eric Park"
email = "me@ericswpark.com"

[signing]
behavior = "drop"
backend = "gpg"
key = "5FB88B4C0425F58385A5C6D62958C7EFD5DCDB0D"

[git]
sign-on-push = true

[ui]
default-command = "log"
