#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Eric Park"
email = "me@ericswpark.com"

[signing]
behavior = "drop"
backend = "gpg"
key = "EC5CFCBD9D7B238842B0F5D496CECB4A9DF00B3B"

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"]
tug- = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[git]
sign-on-push = true

[ui]
default-command = "log"
